services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OliverThiele\OtIrrebuttons\:
    resource: '../Classes/*'

  OliverThiele\OtIrrebuttons\DataProcessing\IrreButtonsProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'ot-irrebuttons-processor'
